Repository dowhiledev/nomos, pull requests merged in 2025-06, with the labels that each got.

#27 Pass LLM kwargs to underline LLM model if defined
  nomos/cli.py
  nomos/config.py
Labels: bug

#28 Add flow memory module and BM25 retriever implementation
  .pre-commit-config.yaml
  README.md
  examples/barista/barista.py
  examples/barista/config.barista.yaml
  nomos/__init__.py
  nomos/cli.py
  nomos/config.py
  nomos/core.py
  nomos/llms/base.py
  nomos/llms/google.py
  nomos/llms/mistral.py
  nomos/llms/openai.py
  nomos/memory/base.py
  nomos/memory/flow.py
  nomos/memory/summary.py
  nomos/models/__init__.py
  nomos/models/agent.py
  nomos/models/flow.py
  nomos/types.py
  nomos/utils/flow_utils.py
  nomos/utils/generator.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_core.py
  tests/test_flow.py
  tools/base-image/main.py
  tools/base-image/src/yaml_to_mermaid.py
  tools/visual-builder/package-lock.json
Labels: enhancement

#30 Replace Sofia references with Nomos
  examples/barista/barista.py
  nomos/constants.py
  nomos/core.py
  nomos/memory/__init__.py
  nomos/models/__init__.py
  nomos/models/agent.py
  nomos/types.py
  nomos/utils/__init__.py
  nomos/utils/logging.py
  tests/conftest.py
  tests/test_core.py
  tools/visual-builder/vercel.json
Labels: codex

#32 Fix memory entry bug and implement token counting
  nomos/llms/base.py
  nomos/llms/openai.py
  nomos/memory/flow.py
  nomos/memory/summary.py
  poetry.lock
  pyproject.toml
  tests/test_memory.py
Labels: codex

#33 Enable Python 3.9 support
  .github/workflows/lint-and-typecheck.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  nomos/core.py
  nomos/models/agent.py
  nomos/utils/utils.py
  poetry.lock
  pyproject.toml
  tools/base-image/main.py
Labels: codex

#36 Support NOMOS logging env vars
  README.md
  examples/barista/barista.py
  examples/barista/barista_with_config.py
  nomos/utils/logging.py
Labels: documentation

#37 Add built-in FastAPI server
  examples/barista/config.barista.yaml
  nomos/__init__.py
  nomos/api/__init__.py
  nomos/api/agent.py
  nomos/api/app.py
  nomos/api/db.py
  nomos/api/models.py
  nomos/api/session_store.py
  nomos/api/static/index.html
  nomos/api/tools/__init__.py
  nomos/api/yaml_to_mermaid.py
  nomos/cli.py
  nomos/config.py
  nomos/server.py
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tools/base-image/.dockerignore
  tools/base-image/.gitignore
  tools/base-image/Dockerfile
  tools/base-image/README.md
  tools/base-image/entrypoint.sh
  tools/base-image/requirements.txt
  tools/base-image/src/tools/__init__.py
Labels: documentation

#39 Refactor decision model outputs
  docs/docs/content/docs/api/rest-api.mdx
  examples/barista/barista_with_config.py
  nomos/core.py
  nomos/models/agent.py
  tests/test_core.py
Labels: bug, documentation

#40 Allow WebSocket session creation
  docs/docs/content/docs/api/websocket.mdx
  nomos/api/app.py
Labels: documentation

#44 Add py.typed for typing support
  CHANGELOG.md
  nomos/py.typed
  pyproject.toml
Labels: codex

#45 Refactor yaml_to_mermaid logging
  nomos/api/yaml_to_mermaid.py
Labels: documentation

#50 Update changelog for 0.2.2
  CHANGELOG.md
Labels: codex

#51 Add TS SDK tests and npm release workflow
  .github/workflows/npm-publish.yml
  .github/workflows/sdk-ts-test.yml
  sdk/ts/test/nomosclient.test.ts
Labels: codex

#60 Add docker compose for visual builder
  tools/visual-builder/README.md
  tools/visual-builder/docker.compose.yml
  tools/visual-builder/frontend/Dockerfile
Labels: codex

#62 Update Visual Builder docs
  tools/visual-builder/README.md
Labels: documentation

#64 Testing Framework for Nomos Agents
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  examples/financial-advisor/__init__.py
  examples/financial-advisor/config.agent.yaml
  examples/financial-advisor/conftest.py
  examples/financial-advisor/test_agent.py
  nomos/__init__.py
  nomos/testing/__init__.py
  nomos/testing/eval.py
  tests/conftest.py
Labels: enhancement

#68 Add YAML-based test runner
  CHANGELOG.md
  README.md
  examples/general-bot/config.agent.yaml
  examples/general-bot/tests.agent.yaml
  nomos/__init__.py
  nomos/cli.py
  nomos/core.py
  nomos/models/agent.py
  nomos/testing/__init__.py
  nomos/testing/e2e.py
  nomos/testing/yaml_runner.py
  nomos/testing/yaml_tests.py
Labels: documentation

#70 CrewAI, Langchain tool support + Fixes & Improvements for Package Tools
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  docs/index.html
  nomos/__init__.py
  nomos/config.py
  nomos/core.py
  nomos/models/agent.py
  nomos/models/tool.py
  nomos/utils/utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_core.py
Labels: bug, enhancement

#72 Logging configuration
  nomos/cli.py
  nomos/config.py
  nomos/core.py
  nomos/utils/logging.py
Labels: documentation

#77 Add external tool type selection
  tools/visual-builder/frontend/src/components/dialogs/ToolEditDialog.tsx
  tools/visual-builder/frontend/src/components/nodes/ToolNode.tsx
  tools/visual-builder/frontend/src/components/panels/NodeEditPanel.tsx
  tools/visual-builder/frontend/src/models/nomos.ts
  tools/visual-builder/frontend/src/types/index.ts
  tools/visual-builder/frontend/src/utils/nomosYaml.ts
  tools/visual-builder/frontend/src/utils/validation.ts
Labels: documentation

#81 Improve auto arrange
  support/visual-builder/frontend/.env.example
  support/visual-builder/frontend/src/components/ChatPopup.tsx
  support/visual-builder/frontend/src/utils/autoArrange.ts
Labels: documentation

#86 Improve CLI usability with version flag
  README.md
  docs/cli-usage.md
  docs/configuration.md
  nomos/cli.py
  support/schemas/.nomos.json
  tests/test_cli.py
Labels: documentation

#93 Nomos Init is outdated
  .gitignore
  docs/configuration.md
  nomos/cli.py
  nomos/config.py
  nomos/constants.py
  nomos/core.py
  nomos/models/agent.py
  nomos/utils/generator.py
  poetry.lock
  pyproject.toml
  tests/test_cli.py
Labels: bug, documentation

#96 Fix for Tools with No Types Defines Fails
  cookbook/examples/barista/config.agent.yaml
  cookbook/examples/financial-advisor/config.agent.yaml
  nomos/config.py
  nomos/core.py
  nomos/models/tool.py
  nomos/utils/utils.py
  support/schemas/.nomos.json
  tests/conftest.py
  tests/test_core.py
Labels: bug

#100 Add interactive training mode
  README.md
  docs/cli-usage.md
  nomos/cli.py
  nomos/core.py
  nomos/llms/base.py
  nomos/models/agent.py
  tests/test_cli.py
  tests/test_core.py
Labels: documentation
