Repository dowhiledev/nomos, pull requests merged in 2025-07, with the labels that each got.

#116 Add async tool support
  nomos/core.py
  nomos/models/tool.py
  tests/test_async_tools.py
Labels: documentation

#118 Docs Website Init
  docs/Showcase.mdx
  docs/cli-usage.mdx
  docs/community.mdx
  docs/configuration.mdx
  docs/contributing-guidelines.mdx
  docs/deployment.mdx
  docs/docs.json
  docs/examples.mdx
  docs/faq.mdx
  docs/flow-management.mdx
  docs/getting-started.mdx
  docs/introduction.mdx
  docs/llm-support.mdx
  docs/md/cli-usage.md
  docs/md/community.md
  docs/md/configuration.md
  docs/md/deployment.md
  docs/md/examples.md
  docs/md/flow-management.md
  docs/md/getting-started.md
  docs/md/llm-support.md
  docs/privacy-policy.mdx
  docs/support.mdx
  docs/terms-of-service.mdx
Labels: documentation

#87 MCPServer as Tool Support
  cookbook/examples/nomos-git-bot/config.agent.yaml
  docs/md/configuration.md
  nomos/config.py
  nomos/core.py
  nomos/llms/base.py
  nomos/models/agent.py
  nomos/models/mcp.py
  nomos/models/tool.py
  nomos/utils/misc.py
  nomos/utils/utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_core.py
  tests/test_model.py
  tests/test_utils.py
  uv.lock
Labels: enhancement

#126 Display diagram in notebook
  cookbook/wikibase_agent.ipynb
  nomos/core.py
  nomos/utils/utils.py
  poetry.lock
Labels: documentation

#163 External APIs as tools
  cookbook/examples/master-roshi/config.agent.yaml
  cookbook/examples/nomos-git-bot/config.agent.yaml
  docs/community/showcase.mdx
  docs/configuration.mdx
  docs/guides/index.mdx
  docs/tools/external-tools.mdx
  nomos/config.py
  nomos/core.py
  nomos/models/tool.py
  nomos/tools/api.py
  nomos/tools/mcp.py
  nomos/tools/models.py
  nomos/utils/utils.py
  tests/conftest.py
  tests/test_api_tools.py
  tests/test_core.py
  tests/test_model.py
  tests/test_tracing.py
Labels: New Feature
